[package]
name = "tran"
version = "0.1.3"
description = "Tran"
authors = ["Borber"]
license = "MIT"
repository = ""
edition = "2021"


[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [
    "global-shortcut-all",
    "process-all",
    "system-tray",
    "window-all",
    "shell-open",
] }

# For base
once_cell = "1"
anyhow = "1"
parking_lot = { version = "0.12", features = ["nightly"] }

tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["default", "gzip", "json"] }


serde = { version = "1", features = ["derive"] }
serde_json = "1"

# For window
window-shadows = "0.2"
mouse_position = "0.1"
selection = "1"

# For URL
urlencoding = "2"

# For clipboard
arboard = { version = "3", default-features = false }

# For language detection
lingua = { version = "1.6", default-features = false, features = [
    "chinese",
    "english",
] }

# For random
fastrand = "2"


[features]
custom-protocol = ["tauri/custom-protocol"]

[build]
rustflags = ["-Z", "threads=8"]

[target.'cfg(unix)'.dependencies]
openssl = { version = '0.10', features = ["vendored"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
