[package]
name = "tran"
version = "0.1.0"
description = "Tran"
authors = ["Borber"]
license = ""
repository = ""
edition = "2021"


[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [
    "global-shortcut-all",
    "process-all",
    "system-tray",
    "window-all",
    "shell-open",
] }

once_cell = "1"

tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }


serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

window-shadows = "0.2"

mouse_position = "0.1"
arboard = "3"
enigo = "0.1"
anyhow = "1.0.75"
urlencoding = "2.1.3"

[features]
custom-protocol = ["tauri/custom-protocol"]


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
