identifier = "panel"
description = "Capability for the panel window"
windows = ["panel"]
permissions = [
    "event:allow-listen",
    "window:allow-show",
    "window:allow-hide",
    "window:allow-set-size",
    "window:allow-set-focus",
    "window:allow-set-position",
    "window:allow-start-dragging",
]
platforms = ["linux", "macOS", "windows"]
