name: "Test build"
on:
  push:
    branches:
      - master

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        lang: [zh-en, zh-jp]
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install frontend dependencies
        run: pnpm install
      - name: Install lua
        use: leafo/gh-actions-lua@v10
      - name: Confirm language
        env:
          MATRIX_LANG: ${{ matrix.lang }}
        run: lua ./scripts/lang.lua
      - name: Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
