name: "Test build"
on:
  push:
    branches:
      - master

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        lang: [zh_en, zh_jp]
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install frontend dependencies
        run: pnpm install
      - name: Install deno
        uses: denoland/setup-deno@v1
          with:
            deno-version: canary
      - name: Confirm language
        env:
          MATRIX_LANG: ${{ matrix.lang }}
        run: deno run -A  script/lang.ts
      - name: Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add tag
        env:
          MATRIX_LANG: ${{ matrix.lang }}
        run: deno run -A script/tag.ts
